apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: everest-operator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: everest-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: everest-operator
  apiGroup: rbac.authorization.k8s.io
