apiVersion: v2
name: everest
displayName: Percona Everest
description: A cloud-native database platform
version: 0.0.0
appVersion: 0.0.0
type: application
kubeVersion: ">=1.27.0-0"
dependencies:
- name: common
  version: 0.0.1
  repository: "file://charts/"
- name: db-namespace
  version: 0.0.1
  repository: "file://charts/"
  condition: dbNamespace.enabled
