{{- range $i, $ns := .Values.namespaces }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: everest-monitoring
  namespace: {{ $ns.name }}
spec:
  targetNamespaces:
  - {{ $ns.name }}
  upgradeStrategy: Default
{{- end }}
