{{- if not (lookup "v1" "Secret" .Release.Namespace "everest-accounts" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    insecure-password/admin: "true"
    helm.sh/resource-policy: keep
data:
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml.tpl") . | b64enc }}
{{- end }}
