apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    insecure-password/admin: "true"
    helm.sh/hook: pre-install
data:
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml.tpl") . | b64enc }}
