{{- if not (lookup "v1" "Secret" .Release.Namespace "everest-jwt" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
  annotations:
    helm.sh/resource-policy: keep
data:
  id_rsa: {{ genPrivateKey "rsa" | b64enc  }}
{{- end }}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace "everest-accounts" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  namespace: {{ .Release.Namespace }}
  annotations:
    insecure-password/admin: "true"
    helm.sh/resource-policy: keep
data:
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml.tpl") . | b64enc }}
{{- end }}
