apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: database-operators
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
  upgradeStrategy: Default

