apiVersion: v1
kind: Service
metadata:
  name: packageserver-service
  namespace: {{ .Values.olm.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "5443"
    port: 5443
    protocol: TCP
    targetPort: 5443
  selector:
    app: packageserver
  type: ClusterIP
